### ISSUE TITLE
Arrow Key Control Scheme

### ISSUE THREAD

**Issue by MayMoonsley** [willbmartin/rune-search#2]
A control scheme using the arrow keys would be useful. (I'm going to work on this, but I just want an issue in place for it because issues are fun.)

**Comment by willmartian** [comment]
Yeah this is something that is super needed and is high priority. 

I'm thinking something like: Left and right arrow keys control which letter you are pivoting on, while up and down arrow keys control the orientation of the move from that position? Let me know if you had something else in mind.
